ktor:
  application:
    modules:
      - sample.study.ApplicationKt.module
  deployment:
    port: 8080

application:
  response:
    serialization:
    pretty: true


# java -Dlogback.configurationFile=logback-local.xml -jar ./build/libs/com.sample.ktor_example-all.jar -config=application.yaml -config=application-local.yaml