version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user12#$
      POSTGRES_DB: notice
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:


#docker-compose -f postgres-docker.yml up -d