version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user12#$
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
volumes:
  pg_data:


#docker-compose -f postgres-docker.yml up -d

#  CREATE TABLE notice (
#  id SERIAL PRIMARY KEY,
#  title VARCHAR(255) NOT NULL,
#  contents VARCHAR(4096) NOT NULL,
#  author VARCHAR(50) NOT NULL,
#  date VARCHAR(50) NOT NULL
#  );

# docker exec -it postgres_local psql -U user -d myapp